language: bash
services: docker

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - image="ruby-1.9.3p551"

script:
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"
  - docker run -it "$image" env
  - docker run -it "$image" ruby -v
  - docker run -it "$image" gem -v
  - docker run -it "$image" bundler -v
  
after_script:
  - docker images

# vim:set et ts=2 sw=2: